import telebot
bot = telebot.TeleBot("6898080037:AAE0TxszZmRQh1b-nZDUxMOIx1oxcvoj2ew")
espresso = open('venv/coffee/espresso.jpg', 'rb')
americano = open('venv/coffee/americano.jpg', 'rb')
latte = open('venv/coffee/latte.jpg', 'rb')
kapuchino = open('venv/coffee/kapuchino.jpg', 'rb')
affogato = open('venv/coffee/affogato.jpg', 'rb')
fcoffee = open('venv/coffee/f-coffee.jpg', 'rb')
fwhite = open('venv/coffee/fwhite.jpg', 'rb')
raw = open('venv/coffee/raw.jpg', 'rb')
lattef = open('venv/coffee/lattef.jpg', 'rb')
lattekb = open('venv/coffee/lattekb.jpg', 'rb')
latteL = open('venv/coffee/latteL.jpg', 'rb')
latteM = open('venv/coffee/latteM.jpg', 'rb')
btlatte = open('venv/coffee/btlatte.jpg', 'rb')
rawC = open('venv/coffee/rawC.jpg', 'rb')
rawM = open('venv/coffee/rawM.jpg', 'rb')
rawIO = open('venv/coffee/rawIO.jpg', 'rb')


@bot.message_handler(commands=['start'])
def start(message):
    names = f' Привет, {message.from_user.first_name}{message.from_user.last_name}, вот прайс лист:'
    bot.send_message(message.chat.id, names)
    bot.send_photo(message.chat.id, espresso, 'Эспрессо, цена: 90₽')
    bot.send_photo(message.chat.id, americano, 'Американо, цена: 190₽')
    bot.send_photo(message.chat.id, latte, 'Латте, цена: 270₽')
    bot.send_photo(message.chat.id, kapuchino, 'Капучино, цена: 230₽')
    bot.send_photo(message.chat.id, affogato, 'Аффогато, цена: 190₽')
    bot.send_photo(message.chat.id, fcoffee, 'Фильтр-кофе, цена: 170₽')
    bot.send_photo(message.chat.id, fwhite, 'Флэт Уайт, цена: 270₽')
    bot.send_photo(message.chat.id, raw, 'Раф Кофе, цена: 290₽')
    bot.send_photo(message.chat.id, lattef, 'Латте "фисташковый", цена: 270₽')
    bot.send_photo(message.chat.id, lattekb, 'Латте "Крем-Брюле с Маршмеллоу", цена: 270₽')
    bot.send_photo(message.chat.id, latteL, 'Латте "Лаванда", цена: 270₽')
    bot.send_photo(message.chat.id, latteM, 'Латте "Миндальный", цена: 270₽')
    bot.send_photo(message.chat.id, btlatte, 'Черный чай латте, цена: 290₽')
    bot.send_photo(message.chat.id, rawC, 'Раф "Кокосовый десерт", цена: 290₽')
    bot.send_photo(message.chat.id, rawM, 'Раф "Масала", цена: 290₽')
    bot.send_photo(message.chat.id, rawIO, 'Раф "Инжир-Орхидея", цена: 290₽')
    bot.send_location(message.chat.id, 55.818304, 37.573529)


bot.polling(none_stop=True)
